import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';

import './globals.css'
import styles from './styles.module.css'
import { Theme } from '@radix-ui/themes';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Main } from 'next/document';
import MainWrapper from '@/components/MainWrapper';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html suppressHydrationWarning lang="en">
         <body className={inter.className}>
            <MainWrapper>
               {children}
            </MainWrapper>
         </body>
      </html>
   )
}
